[versions]
# We need to enforce that the versions we use are the same as AOSP to ensure compatibility.
# 1.3.61 Android 11
# 1.4.30 Android 12
# 1.6.10 Android 13
# 1.7.20 Android 13 (QPR2)
# 1.8.10 Android 14
# 1.9.0 Android 14 (QPR2)
# Check:
# https://android.googlesource.com/platform/external/kotlinc/+/refs/tags/android-14.0.0_r29/build.txt
kotlin = "1.9.0"

androidGradle = "8.1.2"
protobuf = "0.9.4"
ktlint = "11.5.0"
